# Generated by Django 2.1.4 on 2018-12-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_auto_20181211_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
